version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
  heimdall_api:
    container_name: heimdall-api
    #restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    environment:
      DB_URI: mongodb://mongodb
      DB_NAME: heimdall_api
      PORT: 3000
      CRON_EXPRESSION: "*/2 * * * * *"
